export const CREATE_PROJECT = "CREATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const ASSIGN_STUDENTS = "ASSIGN_STUDENTS";
export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT";
export const CLEAR_SELECTED_PROJECT = "CLEAR_SELECTED_PROJECT";
